# Generated by Django 5.1.3 on 2025-02-22 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalstaff',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='nucleus.department'),
        ),
    ]
