# Generated by Django 5.1.3 on 2025-02-23 06:19

from django.db import migrations

def copy_user_data(apps, schema_editor):
    OldUser = apps.get_model('auth', 'User')  
    NewUser = apps.get_model('nucleus', 'MedicalStaff')  

    for old_user in OldUser._default_manager.all():
        NewUser.objects.create(
            id=old_user.id,
            username=old_user.username,
            password=old_user.password,
            email=old_user.email,
            is_staff=old_user.is_staff,
            is_active=old_user.is_active,
            is_superuser=old_user.is_superuser,
            date_joined=old_user.date_joined
        )

class Migration(migrations.Migration):

    dependencies = [
        ('nucleus', '0002_alter_medicalstaff_department'),
    ]

    operations = [
        migrations.RunPython(copy_user_data),
    ]
