# Generated by Django 5.1.3 on 2025-02-22 12:18

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nucleus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_type', models.CharField(choices=[('morning', 'Ca sáng'), ('afternoon', 'Ca chiều'), ('night', 'Ca đêm')], max_length=10)),
                ('date', models.DateField(default=datetime.date.today)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='nucleus.department')),
            ],
            options={
                'db_table': 'schedule_shift',
                'unique_together': {('shift_type', 'date', 'department')},
            },
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_schedules', to='schedule.shift')),
                ('staff', models.ManyToManyField(related_name='work_schedules', to='nucleus.medicalstaff')),
            ],
        ),
    ]
